#!/bin/sh
/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-10min.png --start end-10min --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE LINE3:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-hour.png --start end-60min --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE LINE3:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-6hour.png --start end-6h --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE LINE3:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-day.png --start end-1d --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE DEF:TemperatureMin=powertemp.rrd:Temperature:MIN DEF:TemperatureMax=powertemp.rrd:Temperature:MAX CDEF:TemperatureRange=TemperatureMax,TemperatureMin,- LINE1:TemperatureMin: AREA:TemperatureRange#0000FF11:"Error Range":STACK LINE1:TemperatureMin#0000FF33:"Min" LINE1:TemperatureMax#0000FF33:"Max" LINE1:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-week.png --start end-7d --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE DEF:TemperatureMin=powertemp.rrd:Temperature:MIN DEF:TemperatureMax=powertemp.rrd:Temperature:MAX CDEF:TemperatureRange=TemperatureMax,TemperatureMin,- LINE1:TemperatureMin: AREA:TemperatureRange#0000FF11:"Error Range":STACK LINE1:TemperatureMin#0000FF33:"Min" LINE1:TemperatureMax#0000FF33:"Max" LINE1:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-month.png --start end-1month --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE DEF:TemperatureMin=powertemp.rrd:Temperature:MIN DEF:TemperatureMax=powertemp.rrd:Temperature:MAX CDEF:TemperatureRange=TemperatureMax,TemperatureMin,- LINE1:TemperatureMin: AREA:TemperatureRange#0000FF11:"Error Range":STACK LINE1:TemperatureMin#0000FF33:"Min" LINE1:TemperatureMax#0000FF33:"Max" LINE1:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-year.png --start end-1year --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE DEF:TemperatureMin=powertemp.rrd:Temperature:MIN DEF:TemperatureMax=powertemp.rrd:Temperature:MAX CDEF:TemperatureRange=TemperatureMax,TemperatureMin,- LINE1:TemperatureMin: AREA:TemperatureRange#0000FF11:"Error Range":STACK LINE1:TemperatureMin#0000FF33:"Min" LINE1:TemperatureMax#0000FF33:"Max" LINE1:Temperature#0000FF:"Average"

/usr/bin/rrdtool graph /home/uncle_fungus/temp_monitor/graphs/temp-10year.png --start end-10year --width=1400 --end now --slope-mode --no-legend --vertical-label ˚C --lower-limit 0 --alt-autoscale-max DEF:Temperature=/home/uncle_fungus/powertemp.rrd:Temperature:AVERAGE DEF:TemperatureMin=powertemp.rrd:Temperature:MIN DEF:TemperatureMax=powertemp.rrd:Temperature:MAX CDEF:TemperatureRange=TemperatureMax,TemperatureMin,- LINE1:TemperatureMin: AREA:TemperatureRange#0000FF11:"Error Range":STACK LINE1:TemperatureMin#0000FF33:"Min" LINE1:TemperatureMax#0000FF33:"Max" LINE1:Temperature#0000FF:"Average"
